### ISSUE TITLE
Fix i18n issue

### ISSUE THREAD

**Issue by librehat** [librehat/com.librehat.yahooweather#10]
Currently it doesn't load translations. Need to find out the new API/ABI in Plasma 5

**Comment by pejakm** [comment]
Just rename `com.librehat.yahooweather.mo` to `plasma_applet_com.librehat.yahooweather.mo`

Tested and works.

```
% lsl /usr/share/locale/sr@ijekavian/LC_MESSAGES/*yahoo*
-rw-r--r-- 1 root root 5,3K 11. апр. у 16:33 '/usr/share/locale/sr@ijekavian/LC_MESSAGES/plasma_applet_com.librehat.yahooweather.mo'
```

**Comment by librehat** [comment]
Which also means you need to put those files into system-wide `/usr/share/locale`? I feel reluctant to install them system-widely. Also I haven't written a proper CMake file to do system-wide installation.

**Comment by pejakm** [comment]
> I feel reluctant to install them system-widely.

Translations only work if widget is installed (on system). AFAIK, temporary plasma glitch (could be fixed in future).

**Comment by librehat** [comment]
I know. They really should implement it. (It used to work in KDE4 if installed into current user directory)
