### ISSUE TITLE
在Ubuntu16.04下panel上的图标消失不见

### ISSUE THREAD

**Issue by da-liii** [librehat/com.librehat.yahooweather#11]

**Comment by librehat** [comment]
KDE 4 or Plasma 5?

It can't be used in panel in Plasma 5 yet

**Comment by da-liii** [comment]
Plasma 5, 刚装好的时候Panel上的图标没法显示，点击之后是可以弹出天气的描述的
现在已经可以正常显示Panel上的图标了

**Comment by librehat** [comment]
奇怪。
