### ISSUE TITLE
Bad url?

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#15]
Not sure if you are releasing the version at the commit "Mark new version" at fb0b5cbc0d7255906470c5c99138e661e3c35e95 but the work-around url now in the code seems to be bad and can't be accessed: xml.weather.yahooapis.com
This one does work:
xml.weather.yahoo.com
-gene

**Comment by librehat** [comment]
The workaround no longer work... I'll release a new version containing more improvements later.

**Comment by librehat** [comment]
Please check out `5.1.0`. :smirk_cat:
