### ISSUE TITLE
UV index is actually pressure rising indication

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#33]
Would prefer wind arrow to right of speed instead of before, just my opinion.
Also a rising/falling/steady arrow after pressure would be nice.

**Comment by librehat** [comment]
The arrow is normally prepend to wind speed (as I saw from similar weather widgets on GNOME 3).

Do we have the data for rising/falling/steady?

**Comment by smitgd** [comment]
Yes, I agree, the wind direction is usually before the value.

Yes, we do have pressure direction called m_atmosphereRising which is assigned from results.atmosphere.rising. Per yahoo documentation for old RSS/XML style API:
0 - steady
1 - rising
2 - falling
 However, I think there may be a problem with its usage in that it is already used and is displayed as the value for "UV Index" (see Weather.qml at line 118).  Unless I am missing something, this doesn't seem right. Also, I don't see any field in the raw returned data using the current API for "uv index". This may explain why UV Index is usually zero since it has recently been clear skies here with constant (steady) barometric pressure the last several days. So I think maybe UV Index field should be removed since there is no data for it?

**Comment by smitgd** [comment]
FYI, no change to widget occurred after reinstalling latest HEAD commit c08dc9f81980b49028cf0c82 because version has been bumped, i.e., must do 
plasmapkg2 -u ~/com.librehat.yahooweather-**5.2.0**.plasmoid
With this, changes look good!
