### ISSUE TITLE
Sunrise/Sunset time from yahoo has missing leading 0 when minute < 10

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#36]
When the minutes in sunrise or sunset time arrive from yahoo is 0-9, the leading 0 is discarded and looks non-standard. E.g., should see "Sunset: 8:07 pm". Instead you see "Sunset: 8:7 pm".  A fix-up function is need to handle this. I will post a pull request with a proposed fix that works for me.

**Comment by librehat** [comment]
Merged.
