### ISSUE TITLE
Proposed change to add 24-hour time format

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#39]
I am submitting a pull request that allows for optional selection of 24-hour time format. It is selected via a "check box" added to the "General" configuration screen (default, not selected, i.e., the 12 hour format returned by yahoo).
This affects the time fields in sunset and sunrise as well as the field that shows the time and date of the data from yahoo along the top. I did notice that the data for this field is "lastBuildData". This is actually only the date/time of the query response received from yahoo and is pretty meaningless since it just show the current date/time and does not show the date/time of the collection by yahoo of the latest weather data. A more meaningful field for this is "pubDate" that shows when weather data is actually updated. I took the liberty of using the more honest "pubDate" for this field instead. (Unfortunately, the pubDate is sometimes more then 1 hour behind the query time which explains the lag in the current temperature vs. the yahoo site.)

**Comment by librehat** [comment]
Thanks.
