### ISSUE TITLE
Change forecast temperature separator from ~ to / and reverse temperature order

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#41]
The separator between the hi and lo forecast temperatures, a tilde ("~"), looks somewhat like a minus ("-"). When the temperatures are negative (below zero) the display looks like this (extreme example with temperatures forced negative in the code):
![original](https://cloud.githubusercontent.com/assets/18202740/14757284/e2bc6276-08bf-11e6-8624-727e5eb09a52.png)
I propose changing the separator to a slash ("/") which, I think, improves the display:
![proposed](https://cloud.githubusercontent.com/assets/18202740/14757341/63a4858a-08c0-11e6-8cec-345239a2b067.png)
The change also shows a proposed change in the order to hi/lo. I checked several weather sites and apps and the forecasted high is always before (or above) the low.

**Comment by librehat** [comment]
Maybe instead we should put them into separate rows like:

day
icon
hi
lo

**Comment by smitgd** [comment]
Change the pull request to put hi above lo like you recommend. Actually, that was my first choice but thought maybe you would prefer to keep hi-lo on same line.
In making this change, I tried to assign the lo temp a non-default color (_blue_ for cold like yahoo weather app) but with transparent KDE theme it was sometimes hard to see depending on the background. So I just kept both as default color.

**Comment by smitgd** [comment]
That was actually my first choice (add a new row) but couldn't get the spacing between the hi and lo temp rows to look right. Will try again.

**Comment by librehat** [comment]
Fix merged
