### ISSUE TITLE
If pressure unit is "Atmosphere" result always rounds to exactly 1

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#45]
I think when atmospheric pressure express in "Atmosphere" it will range from slight below to slightly above 1.00. The current code does the correct conversion from mbar to atmospheres but rounds to nearest integer so the result is _always_ 1. 
In function mbarToAtm() need to change in last line from "k.toFixed(0)" to "k.toFixed(2)".

**Comment by smitgd** [comment]
This appears to be consolidated with the pull req #44 that includes the change for hi and lo temp order. Hope this doesn't cause a problem.

**Comment by smitgd** [comment]
Now on a new/separate pull request.

**Comment by librehat** [comment]
Fix merged
