### ISSUE TITLE
console.debug() not printing in fedora fc23

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#47]
Just a question, probably not a problem with weather app:
When I launch the weather widget with plasmashell or plasmawindowed I don't see any console.debug() outputs print with fedora 23. No problem doing same with debian. Is there a way to enable/disable console.debug() messages that might be turned off in fedora? Some suggested it is a compile option for the fedora build of QT vs. debian. Any ideas?
As a test work around, on fedora I have replaced console.debug with console.info so I can see the messages.

**Comment by librehat** [comment]
I'm not sure about this, you might want to ask people in #fedora-kde on IRC (freenode)
