### ISSUE TITLE
Fix bugs regarding query retries, bad WOEID detection and 24-hr display

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#48]
Note: Updated items 1 and 2 only since the descriptions were unclear. Described solutions have so far been rejected by project but work for me. Items 3-5 have been accepted and merged.

This is a list of various somewhat related bugs I have noticed and have fixed:
1. Query fails don't display error message in widget. E.g., if network is down, after refresh only see circular busy indicator with no other hint as to the problem (no "Please check network" message appears). Proposal is to see busy indicator over the errstring message with retries continuing every 10 seconds in background. Also, show the errstring message only after about 5 retries (50 seconds) to avoid seeing the errstring (but still see busy indicator) after a reboot and during transient network drop-outs.
2. With widget running OK and network up, if network then goes down, after a refresh, often "readyState" gets stuck at 1 and never goes to 4 (DONE).  So, even with the proposed 
change in item 1, no errstring "check network" message appears in the widget no matter how long you wait. A solution is to start a 50 second timer each time readyState 1 is detected and when it triggers, abort() the current XMLHttpRequest and start another request/query. This always causes readyState 1 and then 4 to occur repeatedly so the errstring can be displayed (and, of course, when network restored, the busy indicator and errstring disappear and weather data appears, which is also the case for item 1).
    3. Typo at one place where resObj was "resOjb". Never executes so never saw runtime error.
    4. If good WOEID (2472005) changed to bad WOEID (247200566) a problem
    was not detected because query.count is 1 but still don't have a full
    response that can be parsed. Must do check to make sure when
    count is 1 that there is a actually a parsable response.
    5. Fix potential bug in new 24-hr display code. Problem not seen
    with current format from yahoo. Also, cleaned up 24-hr code and comments
    with no functional impact.

**Comment by alium** [comment]
same problem with WOEID, please fix

**Comment by librehat** [comment]
I believe the relevant pull request is merged. Reopen if not.
