### ISSUE TITLE
When installed on panel/tray, when icon clicked, some edge info is cut off.

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#59]
![tray](https://cloud.githubusercontent.com/assets/18202740/14976533/84a956da-10da-11e6-991d-3546cd0a7a1c.png)
Also, some days of week run together.
It appears that the default width needs to be bigger. (Various translations also may have this problem, or worse or maybe not?)
I am assuming installation to panel is supported?
Ideally, the widget size should be adjustable via mouse when installed in panel, just like when installed on desktop. However, it does not seem to be.

**Comment by librehat** [comment]
Yeah, we need to make it slightly wider (it works fine on my laptop oddly).
The popup is not adjustable on Plasma 5.

**Comment by smitgd** [comment]
For me works fine on desktop. The screenshot above is on my laptop...
Yes, I think I remember that with maybe KDE3 it was adjustable but at some point that handy feature was removed.

**Comment by librehat** [comment]
I don't think this is a good idea to let user change this layout size.... None of widgets have this setting.

**Comment by librehat** [comment]
Merged.
