### ISSUE TITLE
Widget in tray does not show weather info until expanded (icon clicked)

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#62]
When installed in panel/tray, after KDE log-in, icon "weather-clouds" always appears and the "tool tips" indicate (in English) "Yahoo! Weather Widget"/A Simple Weather Monitor" and does not show the real current conditions. However, once the tray icon is clicked and the full representation of the widget appears, after that the tray icon and tool tips do show the actual current conditions.
Clicking on the tray icon and showing the full widget should not be required for the icon and tool tips to show the real current conditions. They should just automatically appear at KDE log-in.
In addition, it would be nice for the tray icon to also include the current temperature. 
These suggested changes are similar to the features of the more complex widget https://github.com/kotelnik/plasma-applet-weather-widget

**Comment by librehat** [comment]
We need to figure out a way to put backend in common place that both representations(views) can access.

**Comment by smitgd** [comment]
Yes, I noticed that too. Full had to obtain its own data from "backend" instead of just using data already obtained by compact rep. Couldn't figure how to avoid that. Any ideas?

**Comment by librehat** [comment]
We need to keep only one Yahoo instance. But I don't know how to do that at this moment. :/

**Comment by smitgd** [comment]
Since the changes for this are merged I think it can be closed. However, I have another suggested improvement on this that I will write up as a new issue.
