### ISSUE TITLE
Overlap panel icon and temperature values so used panel space is less.

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#67]
Looking closer at the (overly) complex plasmoid https://github.com/kotelnik/plasma-applet-weather-widget I see that when it appears in the "system tray" the icon and temperature values somewhat overlap and take up much less space in the panel but still show the information clearly. I suggest that the yahoo plasmoid use a similar overlapping temperature/icon in the panel instead of the current side-by-side temperature and icon in the panel that requires a non-default wider space.

**Comment by smitgd** [comment]
Made the change but looks bad (temp unreadable over the icon) on default debian "breeze" theme but good on fedora themes. May also have something to do with the screen/monitor.  So maybe keeping them separate will have to do. Another option is to user the "modern" font based black/white "icons" that the weather-widget uses instead of the "realistic" icons presently used, but for only the panel (keep graphical/realistic icons on full size view).
You can see what I have done so far here if you care to look:
https://github.com/smitgd/com.librehat.yahooweather/tree/overlap-temp-icon%2Bfix-cutoff

**Comment by librehat** [comment]
Merged.
