### ISSUE TITLE
weather-* icons changed on fedora update

### ISSUE THREAD

**Issue by smitgd** [librehat/com.librehat.yahooweather#70]
On recent fedora update I noticed that the icons in the weather plasmoid changed to a more "abstract" appearance (e.g., the moon looked like the "death star" with strange clouds over it). This is because the icons for my selected theme "breeze" changed on the update, I think. To return to the more "realistic" icons I had to change my icon theme from "breeze" to "oxygen".
Maybe this is expected and known behaviour but I would prefer to see the "standard" weather-\* icons inside the plasmoid regardless of the icon theme selected in KDE settings. It really surprised me when they changed. I don't see a way to "pin" the icon set to to the "standard" icons, which seem to be oxygen. The only reference I see for this is here:
http://www.notmart.org/index.php/Software/New_QML_components:_IconItem
and it indicates oxygen icons are used only as a last choice (unless oxygen icon theme selected).

**Comment by librehat** [comment]
This is not about Fedora. Breeze icons set updated. The old icons were fallback to Oxygen.
