### ISSUE TITLE
Add an option in settings to set icon style

### ISSUE THREAD

**Issue by librehat** [librehat/com.librehat.yahooweather#72]
Since we've had webfont in the package now, we can provide an option in settings to let user whether to use the built-in webfont, or use the desktop envrionment's icon set. A checkbox (boolean) is enough here.

**Comment by smitgd** [comment]
This will solve my issue #70 (now closed). I.e., use selected theme icons or the webfont "icons". I will try to implement this ASAP.

**Comment by librehat** [comment]
Merged. Thanks.
