### ISSUE TITLE
High cpu use

### ISSUE THREAD

**Issue by kokoko3k** [librehat/com.librehat.yahooweather#79]
On my laptop, when there is no internet connection and the widgets show the spinning animation, the cpu use is very high (it reaches even 40% - i3-3110M CPU @ 2.40GHz).
Maybe is plasma fault, maybe is qt fault, i don't know, but would it be possible to insert a preference to disable the spinning animation and just show a static "refreshing..."?

Thanks and keep up the good work!

**Comment by librehat** [comment]
How do you even know it's this widget's problem?

**Comment by kokoko3k** [comment]
Several things points in that direction:
1) plasmashell process is taking the cpu use i speak about.
2) As soon as the network is back and the spinning circle stops spinning, the cpu is back to 1%
3) if i remove the widget, cpu is back to 1%
4) if i move the widget to the tray area and back to the desktop, for some reason the spinning animation is no more and cpu goes to 1%

I see you closed this one, are you unable to reproduce my findings?
